### ISSUE TITLE
无法访问啦

### ISSUE THREAD

**Issue by javmain** [geemaple/algorithm#1]
https://mp.weixin.qq.com/s?__biz=MzI1NjA4ODU4NQ==&mid=2247483704&idx=1&sn=e21e36e5c485e91ad92e13b66b544863&chksm=ea2d4e5edd5ac7486e0f24cfc9bab54c5c802d7a8ae3c9fc13e7312b2430bcf012a78895487e#rd

**Comment by geemaple** [comment]
最近在更改公众号，忘记在这里删掉了，以后再加回来，抱歉抱歉
